
name: Release Docker Image

on:
  push:
    tags:
      - "*"  # trigger on every tag push (like v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for release creation

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          docker build -t my-image:$tag .

      - name: Save Docker image as tarball
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          docker save my-image:$tag -o my-image-$tag.tar

      - name: Create GitHub Release and upload image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="Docker release $tag" \
            --notes="This is a Docker image release for tag \`$tag\`" \
            --draft \
            my-image-$tag.tar
